# Generated by Django 4.0.1 on 2022-02-17 06:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='myUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(choices=[('ngo', 'NGO'), ('doner', 'Doner'), ('consumer', 'consumer')], default='', max_length=10)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='userdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], default='', max_length=7)),
                ('firstname', models.CharField(default='', max_length=50)),
                ('lastname', models.CharField(default='', max_length=50)),
                ('bdate', models.DateField(default='')),
                ('phoneno', models.CharField(default='', max_length=50)),
                ('aadhar', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodForAll.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='donatefoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodtype', models.CharField(choices=[('rice', 'rice'), ('wheat', 'wheat'), ('corn', 'corn')], default='', max_length=50)),
                ('quantity', models.IntegerField(default='')),
                ('dateofc', models.DateField(default='')),
                ('timeofc', models.TimeField(default='')),
                ('address', models.CharField(default='', max_length=500)),
                ('status', models.CharField(default='Pending', max_length=10)),
                ('image', models.ImageField(default='', upload_to='images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodForAll.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='cartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(default=0, max_length=10)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodForAll.cart')),
                ('foodtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodForAll.donatefoods')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodForAll.myuser'),
        ),
    ]
