# Generated by Django 4.0.1 on 2022-02-17 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodForAll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fooddata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodtype', models.CharField(default='', max_length=50)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodtype', models.CharField(choices=[('rice', 'rice'), ('wheat', 'wheat'), ('corn', 'corn')], default='', max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('dateofc', models.DateField(default='')),
                ('timeofc', models.TimeField(default='')),
                ('address', models.CharField(default='', max_length=500)),
                ('status', models.CharField(default='Pending', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodForAll.myuser')),
            ],
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='foodtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodForAll.fooddata'),
        ),
        migrations.DeleteModel(
            name='donatefoods',
        ),
    ]
