# Generated by Django 4.0.1 on 2022-02-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodForAll', '0002_fooddata_donation_alter_cartitem_foodtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddata',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
