# Generated by Django 4.0.1 on 2022-02-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodForAll', '0003_fooddata_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddata',
            name='message',
            field=models.BooleanField(default=False),
        ),
    ]
