# Generated by Django 4.0.1 on 2022-03-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodForAll', '0004_fooddata_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='foodpack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packName', models.CharField(default='', max_length=50)),
                ('food1', models.CharField(default='', max_length=50)),
                ('food2', models.CharField(default='', max_length=50)),
                ('food3', models.CharField(default='', max_length=50)),
                ('food4', models.CharField(default='', max_length=50)),
                ('available', models.BooleanField(default=False)),
                ('message', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='donation',
            name='foodtype',
            field=models.CharField(choices=[('Rice', 'Rice'), ('Wheat', 'Wheat'), ('Corn', 'Corn'), ('Jowar', 'Jowar'), ('Bajri', 'Bajri'), ('Moong Dal', 'Moong Dal'), ('Masoor Dal', 'Masoor Dal'), ('Urad Dal', 'Urad Dal'), ('Chana Dal', 'Chana Dal'), ('Toor Dal', 'Toor Dal'), ('Rajma', 'Rajma'), ('Soy Bean', 'Soy Bean')], default='', max_length=50),
        ),
    ]
