# Generated by Django 4.0.1 on 2022-03-01 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodForAll', '0005_foodpack_alter_donation_foodtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='packCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(default=0, max_length=10)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodForAll.cart')),
                ('foodpack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodForAll.foodpack')),
            ],
        ),
    ]
