# Generated by Django 4.0.1 on 2022-03-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodForAll', '0007_cartitem_status_packcart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='packcart',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
