# Generated by Django 4.0.1 on 2022-03-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodForAll', '0008_alter_cartitem_status_alter_packcart_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='firstname',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='bdate',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='lastname',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='city',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='state',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='zip',
            field=models.CharField(default='', max_length=50),
        ),
    ]
