# Generated by Django 4.0.1 on 2022-03-06 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodForAll', '0011_cartitem_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donate_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
