# Generated by Django 4.0.1 on 2022-03-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodForAll', '0013_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodpack',
            name='quantity',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='foodpack',
            name='food1',
            field=models.CharField(choices=[('Rice', 'Rice'), ('Wheat', 'Wheat'), ('Corn', 'Corn'), ('Jowar', 'Jowar'), ('Bajri', 'Bajri'), ('Moong Dal', 'Moong Dal'), ('Masoor Dal', 'Masoor Dal'), ('Urad Dal', 'Urad Dal'), ('Chana Dal', 'Chana Dal'), ('Toor Dal', 'Toor Dal'), ('Rajma', 'Rajma'), ('Soy Bean', 'Soy Bean')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='foodpack',
            name='food2',
            field=models.CharField(choices=[('Rice', 'Rice'), ('Wheat', 'Wheat'), ('Corn', 'Corn'), ('Jowar', 'Jowar'), ('Bajri', 'Bajri'), ('Moong Dal', 'Moong Dal'), ('Masoor Dal', 'Masoor Dal'), ('Urad Dal', 'Urad Dal'), ('Chana Dal', 'Chana Dal'), ('Toor Dal', 'Toor Dal'), ('Rajma', 'Rajma'), ('Soy Bean', 'Soy Bean')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='foodpack',
            name='food3',
            field=models.CharField(choices=[('Rice', 'Rice'), ('Wheat', 'Wheat'), ('Corn', 'Corn'), ('Jowar', 'Jowar'), ('Bajri', 'Bajri'), ('Moong Dal', 'Moong Dal'), ('Masoor Dal', 'Masoor Dal'), ('Urad Dal', 'Urad Dal'), ('Chana Dal', 'Chana Dal'), ('Toor Dal', 'Toor Dal'), ('Rajma', 'Rajma'), ('Soy Bean', 'Soy Bean')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='foodpack',
            name='food4',
            field=models.CharField(choices=[('Rice', 'Rice'), ('Wheat', 'Wheat'), ('Corn', 'Corn'), ('Jowar', 'Jowar'), ('Bajri', 'Bajri'), ('Moong Dal', 'Moong Dal'), ('Masoor Dal', 'Masoor Dal'), ('Urad Dal', 'Urad Dal'), ('Chana Dal', 'Chana Dal'), ('Toor Dal', 'Toor Dal'), ('Rajma', 'Rajma'), ('Soy Bean', 'Soy Bean')], default='', max_length=50),
        ),
    ]
