# Generated by Django 4.0.1 on 2022-03-15 06:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodForAll', '0015_packcart_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='mealFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donate_date', models.DateTimeField(default=datetime.datetime.now)),
                ('foodtname', models.CharField(default='', max_length=50)),
                ('quantity', models.CharField(default='', max_length=50)),
                ('dateofc', models.DateField(default='')),
                ('timeofc', models.TimeField(default='')),
                ('address', models.CharField(default='', max_length=500)),
                ('dec', models.CharField(default='', max_length=500)),
                ('status', models.CharField(default='Pending', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodForAll.userdetail')),
            ],
        ),
    ]
