# Generated by Django 4.0.1 on 2022-03-15 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodForAll', '0016_mealfood'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mealFood',
        ),
    ]
